In [1]:
import pandas as pd

In [2]:
coding = pd.read_csv("Coding proposals - Sheet1.csv")

In [3]:
coding

,Presentation title,Industry (where is AI used?) (multi-select possible),AI use (how is AI used?) (multi-select possible),Fairness issue (multi-select possible),Orientation (multi-select not possible)
0,Amazon resume,"""Internal business operations, workplace & lab...",Classification tasks (speech/voice/age recogni...,Disparate impact across social groups,Negative (AI detracts from fairness)
1,AI in Voice Infringement - China 2023 case,?/NA (presentation doesn't talk about specific...,Generative AI,Privacy & surveillance concerns,Negative (AI detracts from fairness)
2,2019 Apple Card Bias Case,"""Finance, banking & insurance""",Classification tasks (speech/voice/age recogni...,Disparate impact across social groups,Negative (AI detracts from fairness)
3,Spotify’s Recommendation System,"Cultural representation, ""Social media, sports...",Recommendation systems,Balancing between different concepts of fairness,Neutral (mixed bag)
4,AI-generated Art/Music,"Cultural representation, ""Social media, sports...",Generative AI,Balancing between different concepts of fairness,Negative (AI detracts from fairness)
...,...,...,...,...,...
56,Auditing the audits': takeaways from analyzing...,"""Government, infrastructure management, social...",NaN,NaN,NaN
57,Biases found in Synthetic or Pseudo Data and D...,Education & academia,NaN,NaN,NaN
58,Claude Interviewer Tool for Research,Education & academia,NaN,NaN,NaN
59,Age and Race Biases in Autonomous Driving Systems,?/NA (presentation doesn't talk about specific...,Classification tasks (speech/voice/age recogni...,NaN,NaN
60,Turnitin AI Detection,Education & academia,Natural Language Processing,NaN,NaN

In [4]:
coding.head()

,Presentation title,Industry (where is AI used?) (multi-select possible),AI use (how is AI used?) (multi-select possible),Fairness issue (multi-select possible),Orientation (multi-select not possible)
0,Amazon resume,"""Internal business operations, workplace & lab...",Classification tasks (speech/voice/age recogni...,Disparate impact across social groups,Negative (AI detracts from fairness)
1,AI in Voice Infringement - China 2023 case,?/NA (presentation doesn't talk about specific...,Generative AI,Privacy & surveillance concerns,Negative (AI detracts from fairness)
2,2019 Apple Card Bias Case,"""Finance, banking & insurance""",Classification tasks (speech/voice/age recogni...,Disparate impact across social groups,Negative (AI detracts from fairness)
3,Spotify’s Recommendation System,"Cultural representation, ""Social media, sports...",Recommendation systems,Balancing between different concepts of fairness,Neutral (mixed bag)
4,AI-generated Art/Music,"Cultural representation, ""Social media, sports...",Generative AI,Balancing between different concepts of fairness,Negative (AI detracts from fairness)

In [5]:
coding.columns

Index(['Presentation title',
       'Industry (where is AI used?) (multi-select possible)',
       'AI use (how is AI used?) (multi-select possible)',
       'Fairness issue (multi-select possible)',
       'Orientation (multi-select not possible)'],
      dtype='str')

In [8]:
coding.rename(columns={"Presentation title": "title", "Industry (where is AI used?) (multi-select possible)": "ind", "AI use (how is AI used?) (multi-select possible)": "use", "Fairness issue (multi-select possible)": "issue", "Orientation (multi-select not possible)": "orientation"}, inplace=True)

In [9]:
coding.columns

Index(['title', 'ind', 'use', 'issue', 'orientation'], dtype='str')

In [13]:
coding['ind'].value_counts()

ind
"Social media, sports, entertainment, & platforms"                                         9
?/NA (presentation doesn't talk about specific industry)                                   8
"Government, infrastructure management, social welfare"                                    8
"Internal business operations, workplace & labor dynamics"                                 7
Education & academia                                                                       7
Healthcare & diagnostics                                                                   4
Housing                                                                                    4
Advertisement & business revenue making                                                    3
"Finance, banking & insurance"                                                             2
Cultural representation, "Social media, sports, entertainment, & platforms"                2
Content moderation (trust & safety)                                                        2
Law                                                                                        1
Content moderation (trust & safety), "Social media, sports, entertainment, & platforms"    1
News & information ecosystem                                                               1
Cultural representation                                                                    1
Name: count, dtype: int64